Filter NaN flows from MIP
powsybl/powsybl-open-rao pull request #1014
Opened 2024-05-17 11:55 UTC by pet-mit

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Bug fix

**What is the current behavior?**

- When sensitivity computation in PRAO fails for a given contingency, a sensitivity failure over-cost is computed, but the flow CNECs of that contingency are still part of the MIP range-action optimization.
This leads to NaN values in MIP (when sensi computation fails, output reference flow value is NaN) and can crash the RAO.
- When the initial sensitivity computation has a failed state, no overcost is reported

**What is the new behavior (if this is a feature change)?**
- MIP fillers that use the flow variable now filter flow CNECs first, and only retains those with a succeeded sensitivity computation status
- Unfortunately, since the status can change between two sensi iterations, we may have to remove or add variables and constraints. Since removing variables and constraints is not possible in OR-Tools, the linear problem's update method now resets the MIP and calls the "fill" method first
- When the initial sensitivity computation has a failed state, the overcost is now reported. This means the RAO can prefer RAs that remove network divergence.
- The OpenRaoMPSolver (that uses OR-Tools under the hood) is now used in unit tests, making the tests more representative of real-time execution

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-05-22 13:08 UTC, phiedw requested changes

2024-05-22 13:08 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolver.java
> +    public boolean minimization() {
I believe the naming convention for boolean getters is: isMinimization() / isMaximization()

2024-05-22 13:09 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
> +        return FillersUtil.getValidFlowCnecs(loopFlowCnecs, sensitivityResult);
(same question for mnecs, and also relative margin with fixed ptdfs)

2024-05-22 13:17 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
> +        // TODO: this is too slow, we can replace it with load-flow computations or security analysis since we don't need sensitivity values
I noticed it was slow for a big test case with many states with applied RAs

2024-05-22 13:17 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
> +        return FillersUtil.getValidFlowCnecs(loopFlowCnecs, sensitivityResult);
working on it, gonna filter those too

2024-05-22 13:19 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolver.java
> +    static double roundDouble(double value, int numberOfBitsToRoundOff) {
it's a static method. I could've put it in a new utils class but thought it wasn't worth it

2024-05-22 15:36 UTC, phiedw requested changes

2024-05-22 15:36 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtil.java
> +    static Set<FlowCnec> getValidFlowCnecs(Set<FlowCnec> flowCnecs, FlowResult flowResult) {
I'm not a huge fan of having two methods with the same name with arguments so similar. We could easily have a class that implements both SensitivityResult and FlowResult (eg any OptimizationResult implementation), and we wouldn't know which method to use.

2024-05-23 07:47 UTC, phiedw approved these changes

2024-05-24 08:39 UTC, merged