Allow multi-curative in second preventive optimisation
powsybl/powsybl-open-rao pull request #1016
Opened 2024-05-17 15:07 UTC by pet-mit

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

Second preventive RAO does not handle CRACs with multiple curative instants

**What is the new behavior (if this is a feature change)?**
It is now possible to run 2nd preventive RAO. However, impossible to fetch temporary results (for example the flow of CNEC monitored in curative2 after application of curative1 CRAs only)

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

2024-05-30 08:56 UTC, bqth29 commented
@pet-mit @phiedw do you think it is still relevant to keep `FlowResult.getFlow(FlowCnec flowCnec, Side side, Unit unit)` now that we defined `FlowResult.getFlow(FlowCnec flowCnec, Side side, Unit unit, Instant instant)`?

2024-06-06 07:34 UTC, phiedw requested changes

2024-06-06 07:34 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +            return flowResult.getFlow(flowCnec, side, unit, optimizedInstant);
I think the method getStateOptimizedBefore also needs rewriting for curative instants (looking at the current code, it looks like it should be broken for anything but the first curative instant)

2024-06-13 15:00 UTC, phiedw submitted a review, later dismissed

2024-06-20 06:42 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/api/FlowResult.java
> +    double getFlow(FlowCnec flowCnec, Side side, Unit unit, Instant instant);
```suggestion
    /**
     * It gives the flow on a {@link FlowCnec}, at a given {@link Instant} and in a given {@link Unit}.
     *
     * @param flowCnec: The branch to be studied.
     * @param side: The side of the branch to be queried.
     * @param unit: The unit in which the flow is queried. Only accepted values are MEGAWATT or AMPERE.
     * @param instant: The optimization instant for which the flow is queried.
     * @return The flow on the branch in the given unit.
     */
    double getFlow(FlowCnec flowCnec, Side side, Unit unit, Instant optimizedInstant);
```

2024-06-20 06:42 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
> +    // TODO add tests
add tests

2024-06-20 06:42 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
> +    // TODO add tests
add tests

2024-06-26 16:06 UTC, bqth29 approved these changes

2024-06-28 08:16 UTC, bqth29 approved these changes

2024-06-28 08:25 UTC, merged