enable back preventive factors after sensi ends in 2P
powsybl/powsybl-open-rao pull request #1079
Opened 2024-07-05 09:41 UTC by MartinBelthle

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-07-05 11:42 UTC, phiedw reviewed
Maybe we should add a small non regression test to be safe

2024-07-08 11:09 UTC, phiedw commented
> Maybe we should add a small non regression test to be safe

It's actually quite difficult to create such a test case on a 12node network, since it requires the MIP giving different results throughout the iterations, so I guess we should just keep the case that revealed the problem in our sensitive test data.

2024-07-09 07:40 UTC, pet-mit requested changes

2024-07-09 07:40 UTC, pet-mit commented on sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityAdapter.java
> +        cnecSensitivityProvider.enableFactorsForBaseCaseSituation();
if i comment this line, the unit test that you added does not fail

2024-07-09 12:50 UTC, merged