WIP: draft version for generic monitoring (voltage + angle)
powsybl/powsybl-open-rao pull request #1092
Opened 2024-07-15 12:58 UTC by benrejebmoh

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-07-18 11:30 UTC, pet-mit commented on generic-monitoring/pom.xml
I would remove "generic" from the name

2024-07-18 11:33 UTC, pet-mit commented on generic-monitoring/src/main/java/com/powsybl/openrao/monitoring/MonitoringInput.java
> +            monitoringInput.physicalParameter = physicalParameter;
what happens if pyhsicalParameter is null?

2024-07-18 12:09 UTC, benrejebmoh commented on generic-monitoring/pom.xml
i put 'generic' temporarily in the name of the module to keep in the same branch the old monitoring module until the validation of this PR

2024-07-18 12:22 UTC, pet-mit requested changes

2024-07-18 12:22 UTC, pet-mit commented on generic-monitoring/src/main/java/com/powsybl/openrao/monitoring/Monitoring.java
> +        if (monitoringInput.getPhysicalParameter().equals(PhysicalParameter.ANGLE)) {
not necessary. can be generic if we only check if any of the applied RAs are InjectionSetpoints.
more generally, I think we can make it cleaner / more generic by doing a "balnce" check before & after the monitoring

2024-07-18 12:22 UTC, pet-mit commented on generic-monitoring/src/main/java/com/powsybl/openrao/monitoring/AppliedNetworkActionsResult.java
I'd prefer if we can remove this class

2024-09-03 12:55 UTC, pet-mit submitted a review, later dismissed

2024-09-26 15:19 UTC, Godelaine requested changes

2024-09-27 11:58 UTC, benrejebmoh commented on data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/FlowCnecImpl.java
> +        return Double.isNaN(power) ? branch.getTerminal(side).getP() * getFlowUnitMultiplier(side) : power;
i am not sure to understand "explicit that you're doing a conversion Ampere/MW"

2024-09-30 12:53 UTC, benrejebmoh commented on data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/FlowCnecImplTest.java
> +        Network network = Mockito.mock(Network.class, Mockito.RETURNS_DEEP_STUBS);
I mocked in purpose the branches to check that computeValue method in FlowCnecImpl calculates correctly side1Value and side2Value. In the TestCase12Nodes.uct network  P on terminal is Nan.

2024-09-30 13:38 UTC, Godelaine commented on data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/FlowCnecImplTest.java
> +        Network network = Mockito.mock(Network.class, Mockito.RETURNS_DEEP_STUBS);
ok, never mind then, could you still remove RETURNS_DEEP_STUBS even if that means a few more lines to mock terminals ?

2024-10-10 13:29 UTC, Godelaine approved these changes

2024-10-10 13:30 UTC, merged