Rao Parameters:  separate business from implementation specific
powsybl/powsybl-open-rao pull request #1101
Opened 2024-07-31 12:08 UTC by pjeanmarie

… acceptable)

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-08-09 16:00 UTC, pjeanmarie commented
separated in multiple PR/
#1112
#1111

2024-11-29 09:33 UTC, pjeanmarie commented on ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
> +        //when(parameters.getRangeActionParameters()).thenReturn(rangeActionParameters);
fixed

2025-01-09 17:05 UTC, phiedw requested changes

2025-01-14 10:05 UTC, pjeanmarie commented on docs/parameters.md
> +  the ones with the PST taps the closest to the initial situation.
fixed the renaming part

2025-01-14 10:05 UTC, pjeanmarie commented on docs/parameters.md
> +  the ones with the HVDC set-points the closest to the initial situation.
fixed

2025-01-14 10:07 UTC, pjeanmarie commented on docs/parameters.md
> +  optimisation problem of the RAO, in the same way as the two types of RangeAction above.
fixed

2025-01-14 10:41 UTC, pjeanmarie commented on docs/parameters.md
> +  when it is set to PREVENTIVE_OBJECTIVE or PREVENTIVE_OBJECTIVE_AND_SECURE.
fixed

2025-01-14 10:49 UTC, pjeanmarie commented on docs/parameters.md
> +    parallel during the <ins>automaton</ins> RAO.
fixed

2025-01-14 11:15 UTC, pjeanmarie commented on docs/parameters.md
> +  topological action improves the objective function by x, with x < solution(depth(n)) x relative-minimum-impact-threshold,
fixed using markdown equation, is it appropriate?

2025-01-14 11:15 UTC, pjeanmarie commented on docs/parameters.md
> +  the ones with the HVDC set-points the closest to the initial situation.
fixed using markdown equation

2025-01-14 11:15 UTC, pjeanmarie commented on docs/parameters.md
> +  the ones with the PST taps the closest to the initial situation.
fixed using markdown equation, is it appropriate?

2025-01-14 13:24 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/json/extensions/JsonMultiThreadingParameters.java
> + * @author Godelaine de Montmorillon {@literal <godelaine.demontmorillon at rte-france.com>}
fixed

2025-01-14 13:24 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/json/extensions/JsonObjectiveFunctionParameters.java
> + * @author Godelaine de Montmorillon {@literal <godelaine.demontmorillon at rte-france.com>}
fixed

2025-01-14 13:25 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/json/extensions/JsonOpenRaoSearchTreeParameters.java
> +@AutoService(JsonRaoParameters.ExtensionSerializer.class)
fixed

2025-01-14 13:25 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/json/extensions/JsonRangeActionsOptimizationParameters.java
> + * @author Godelaine de Montmorillon {@literal <godelaine.demontmorillon at rte-france.com>}
fixed

2025-01-14 13:25 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/json/extensions/JsonTopoOptimizationParameters.java
> + * @author Godelaine de Montmorillon {@literal <godelaine.demontmorillon at rte-france.com>}
fixed

2025-01-14 13:30 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/RangeActionsOptimizationParameters.java
> + * @author Godelaine de Montmorillon {@literal <godelaine.demontmorillon at rte-france.com>}
fixed

2025-01-14 13:30 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/TopoOptimizationParameters.java
> + * @author Godelaine de Montmorillon {@literal <godelaine.demontmorillon at rte-france.com>}
fixed

2025-01-14 13:38 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/LoadFlowAndSensitivityParameters.java
> +    // TODO: do not set if default...
My problem here is that I wish I coult tell the return object is read only, since the value returned can be either real part of the parameters and so it affect the parameters if written, or a new independant object (default case) where the writing will have no effect "outside"

2025-01-14 13:41 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/LoadFlowAndSensitivityParameters.java
> +    // TODO: do not set if default...
I probably should modify this TODO to just add a comment saying it is expected to be read only

2025-01-14 13:47 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/SecondPreventiveRaoParameters.java
> +import com.powsybl.openrao.raoapi.parameters.RaoParameters;
fixed

2025-01-14 13:47 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/MultithreadingParameters.java
> +import com.powsybl.openrao.raoapi.parameters.RaoParameters;
fixed

2025-01-14 13:49 UTC, pjeanmarie commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
> +    private final com.powsybl.openrao.raoapi.parameters.extensions.RangeActionsOptimizationParameters rangeActionParametersExtension;
done for all class duplicated: ObjectiveFunctionParameters, RangeActionsOptimizationParameters, TopoOptimizationParameters

2025-01-14 14:05 UTC, pjeanmarie commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
> +        if (getExecutionCondition(raoParameters).equals(SecondPreventiveRaoParameters.ExecutionCondition.DISABLED)) {
fixed

2025-01-14 14:15 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/extensions/LoadFlowAndSensitivityParameters.java
> +    // TODO: do not set if default...
done

2025-01-16 09:25 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/RaoParametersCommons.java
>      // objective function parameters
done

2025-01-23 13:49 UTC, phiedw approved these changes

2025-01-31 12:58 UTC, merged