[CSA] No longer read AE.isCombinableWithRemedialAction attribute
powsybl/powsybl-open-rao pull request #1130
Opened 2024-09-11 08:02 UTC by bqth29

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
The field isCombinableWithRemedialAction was making the CRAC heavier than needed by adding OnConstraint usage rules even though the behavior is already covered by other usage rules.

**What kind of change does this PR introduce?**
The attribute is no longer read which avoid creating several useless or undesired OnConstraint usage rules for remedial actions.

2024-10-16 12:42 UTC, jipea requested changes

2024-10-16 12:42 UTC, jipea commented on data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/cnec/FlowCnecCreator.java
> +    private static Set<Country> getBranchLocation(Branch<?> branch) {
I think this method is useless now, because there's no more geographical filter

2024-10-17 12:53 UTC, jipea submitted a review, later dismissed

2024-10-23 14:06 UTC, benrejebmoh approved these changes

2024-10-24 07:23 UTC, merged