Rao parameters remove curative stop criterion
powsybl/powsybl-open-rao pull request #1139
Opened 2024-09-18 12:42 UTC by pjeanmarie

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-11-26 09:28 UTC, obrix reviewed
First pass is okay for me, I think some behavior changes were agreed between @pjeanmarie  and @phiedw. I think a more precise look at the comment I placed would be good.

2024-11-26 09:28 UTC, obrix commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
> +            && preventiveOptimalCost > 0
To check @phiedw

2024-11-26 09:28 UTC, obrix commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
> +        ObjectiveFunctionParameters.PreventiveStopCriterion preventiveStopCriterion = raoParameters.getObjectiveFunctionParameters().getPreventiveStopCriterion();
To check @phiedw

2024-11-26 09:28 UTC, obrix commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/parameters/TreeParameters.java
> +                if (parameters.getObjectiveFunctionParameters().getEnforceCurativeSecurity()) {
To check @phiedw

2024-12-12 14:53 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
> +        ObjectiveFunctionParameters.PreventiveStopCriterion preventiveStopCriterion = raoParameters.getObjectiveFunctionParameters().getPreventiveStopCriterion();
I think this logic is correct

2024-12-12 15:02 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/parameters/TreeParameters.java
> +                if (parameters.getObjectiveFunctionParameters().getEnforceCurativeSecurity()) {
This looks correct

2024-12-12 15:36 UTC, phiedw requested changes
I think it might make more sense to rename preventive-stop-criterion to stop-criterion now since it affects both preventive and curative steps

2024-12-12 15:39 UTC, phiedw commented
> I think it might make more sense to rename preventive-stop-criterion to stop-criterion now since it affects both preventive and curative steps

Ah i forgot it's removed in the next pull request anyways so I think it's all good for this pull request! :)

2024-12-12 15:39 UTC, phiedw approved these changes

2025-01-31 13:53 UTC, merged