[CSA] Use GridStateAlterations i
powsybl/powsybl-open-rao pull request #1162
Opened 2024-10-14 09:16 UTC by bqth29

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-10-14 09:43 UTC, bqth29 commented
One question: if the id of an elementary action is the default one, should we export it in the JSON CRAC or not?

2024-11-06 14:48 UTC, phiedw requested changes

2024-11-06 14:48 UTC, phiedw commented on data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractSingleNetworkElementActionAdderImpl.java
> +        return id == null ? String.format("%s_%s_%s", getActionName(), networkElementId, specificAttribute) : id;
rename getActionName to getActionTypeName to avoid confusions between these two methods.

2025-01-17 14:49 UTC, bqth29 commented
too many conflicts, start over when less PRs are being worked on at the same time

2025-01-17 14:49 UTC, closed without merging