Rao parameters put back some extensions values into rao parameters
powsybl/powsybl-open-rao pull request #1191
Opened 2024-11-05 09:21 UTC by pjeanmarie

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2025-01-10 08:43 UTC, phiedw requested changes

2025-01-10 08:43 UTC, phiedw commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/MnecParameters.java
> +    //TODO to remove
Is this todo to be done in this PR?

2025-01-16 09:43 UTC, pjeanmarie commented on ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/MnecParameters.java
> +    //TODO to remove
probably, I removed it

2025-01-16 10:04 UTC, pjeanmarie commented
@phiedw I think I should change the class name identical in parameters and the extension as we do before (for example SearchTreeRaoRangeActionsOptimizationParameters in rao_parameters_separate_business_and_implem_specific). So I will rename:
- MnecParameters -> SearchTreeRaoMnecParameters
- RelativeMarginsParameters -> SearchTreeRaoRelativeMarginsParameters
- LoopFlowParameters -> SearchTreeRaoLoopFlowParameters

2025-01-16 13:46 UTC, pjeanmarie commented on docs/parameters.md
> +### Loop-flow optional parameter
done

2025-01-17 09:21 UTC, pjeanmarie commented on docs/parameters.md
> +### Loop-flow optional parameter
done

2025-01-23 13:02 UTC, phiedw approved these changes

2025-01-31 12:42 UTC, merged