Export execution details
powsybl/powsybl-open-rao pull request #1193
Opened 2024-11-06 16:41 UTC by phiedw

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes #1137 

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

The RaoResult only exports executed steps (for non failing RAOs)

**What is the new behavior (if this is a feature change)?**
We now export either the steps executed or a failure reason (as a string). Also surronded the main parts of the RAO to be able to return a FailedRaoResult instead of crashing when an unexpected RuntimeException happens.

**Does this PR introduce a breaking change or deprecate an API?**
- [x] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [x] The *Breaking Change* or *Deprecated* label has been added
- [x] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

If you use RaoResult.getOptimizationSteps, you will have to replace it with RaoResult.getExecutionDetails

2024-11-08 13:05 UTC, phiedw commented
Part of this PR can actually make debugging harder because you lose access to the stack trace. Should I add a business error log in the catch to log the error and its stack trace?

2024-11-13 15:04 UTC, phiedw commented
> Part of this PR can actually make debugging harder because you lose access to the stack trace. Should I add a business error log in the catch to log the error and its stack trace?

Added a business error

2024-11-28 15:55 UTC, Godelaine requested changes

2024-12-02 15:47 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImplTest.java
> +        setUp();
indeed!

2024-12-02 15:49 UTC, phiedw commented on data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/RaoResultSerializer.java
> +            jsonGenerator.writeStringField(EXECUTION_DETAILS, raoResult.getExecutionDetails());
I'm surprised this was not caught by a unit test, I'll add one

2024-12-05 09:24 UTC, Godelaine approved these changes

2024-12-05 10:42 UTC, merged