Costly optimization of range actions
powsybl/powsybl-open-rao pull request #1243
Opened 2024-12-18 13:09 UTC by bqth29

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
Following #1186, range actions can now be optimized cost-wise in the MIP model.

The `CoreProblemFiller` was split in two files (`MarginCoreProblemFiller` and `CostCoreProblemFiller`) two handle margin or cost optimizations.

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2025-01-15 14:56 UTC, phiedw requested changes

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractCoreProblemFiller.java
> +    protected void addSetPointConstraints(LinearProblem linearProblem, RangeAction<?> rangeAction, State state) {
Keep the comment

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFiller.java
> +     */
keep the comment with the addSetPointConstraints method

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFiller.java
> +    private void addIsVariationConstraint(LinearProblem linearProblem, RangeAction<?> rangeAction, State state) {
add a comment describing the constraint

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFiller.java
> +                if (!(ra instanceof PstRangeAction)) {
add a comment to indicate pst costs are considered in the discreteTapFiller

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
> +                totalTapVariationConstraint.setCoefficient(linearProblem.getTapVariable((PstRangeAction) lastAvailableRangeAction.getLeft(), lastAvailableRangeAction.getRight()), 1.0);
is lb and ub = 0 by default?

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
> +            forceMinMarginToBeNegative(linearProblem);
add a comment to explain we do this to penalize negative margins without rewarding positive margins

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
> +            }
you also check in the method itself, is it possible to remove one of them?

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/AbstractFunctionalCostComputer.java
> +    protected AbstractFunctionalCostComputer(OptimizationResult secondPreventivePerimeterResult, Map<State, OptimizationResult> postContingencyResults) {
Is it always a secondPreventivePerimeterResult or can it be 1P too?

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/MaximumFunctionalCostComputer.java
> +    public MaximumFunctionalCostComputer(OptimizationResult secondPreventivePerimeterResult, Map<State, OptimizationResult> postContingencyResults) {
Is it always a secondPreventivePerimeterResult or can it be 1P too?

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/TotalFunctionalCostComputer.java
> +    public TotalFunctionalCostComputer(OptimizationResult secondPreventivePerimeterResult, Map<State, OptimizationResult> postContingencyResults) {
Is it always a secondPreventivePerimeterResult or can it be 1P too?

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResult.java
> +            return getActivatedNetworkActions().stream().mapToDouble(networkAction -> networkAction.getActivationCost().orElse(0.0)).sum();
why are we only checking network actions here?

2025-01-15 14:56 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +            return new TotalFunctionalCostComputer(secondPreventivePerimeterResult, postContingencyResults).computeFunctionalCost(optimizedInstant);
This will not work for null instant (pre oprimization value)

2025-01-15 15:11 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractCoreProblemFiller.java
> +    protected void addAllRangeActionVariables(LinearProblem linearProblem, RangeAction<?> rangeAction, State state) {
no indeed

2025-01-15 15:19 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractCoreProblemFiller.java
> +    protected void addAllRangeActionVariables(LinearProblem linearProblem, RangeAction<?> rangeAction, State state) {
yes because it is overridden in a child class

2025-01-15 15:21 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
> +                totalTapVariationConstraint.setCoefficient(linearProblem.getTapVariable((PstRangeAction) lastAvailableRangeAction.getLeft(), lastAvailableRangeAction.getRight()), 1.0);
yes

2025-01-15 15:24 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
> +            }
yes, I kept the check in the method and remove the one from your comment

2025-01-15 15:25 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/AbstractFunctionalCostComputer.java
> +    protected AbstractFunctionalCostComputer(OptimizationResult secondPreventivePerimeterResult, Map<State, OptimizationResult> postContingencyResults) {
indeed it can be any optimization result, I will update this

2025-01-15 15:28 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +            return new TotalFunctionalCostComputer(secondPreventivePerimeterResult, postContingencyResults).computeFunctionalCost(optimizedInstant);
In `TotalFunctionalCostComputer`, the method `computeFunctionalCost` is:

```java
public double computeFunctionalCost(Instant instant) {
        return instant == null ? 0.0 : optimizationResult.getFunctionalCost() + streamPostContingencyResultsBeforeInstant(instant).sum();
}
```

Thus, if the instant is null (i.e. pre-optim result), no remedial actions were applied so the cost is null.

2025-01-15 15:43 UTC, bqth29 commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResult.java
> +            return getActivatedNetworkActions().stream().mapToDouble(networkAction -> networkAction.getActivationCost().orElse(0.0)).sum();
I forgot to add range actions, it is fixed now

2025-01-17 08:38 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +            return new TotalFunctionalCostComputer(secondPreventivePerimeterResult, postContingencyResults).computeFunctionalCost(optimizedInstant);
ah correct I missed that part

2025-01-17 08:53 UTC, phiedw approved these changes

2025-01-17 14:15 UTC, phiedw approved these changes

2025-01-17 14:16 UTC, merged