Angle monitoring noglsk
powsybl/powsybl-open-rao pull request #1249
Opened 2024-12-24 11:16 UTC by RoxaneChen02

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes #1202

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-12-24 11:23 UTC, RoxaneChen02 commented
Crash no matter what error occurs in the try (not just missing country code error) is it problematic? Are there cases where you just want to interrupt and still go to the end of the function?

2025-01-06 12:48 UTC, Godelaine requested changes

2025-01-06 12:48 UTC, Godelaine commented on monitoring/src/test/resources/GlskB45test_noScalableZonalData.xml
> +<GLSK_MarketDocument xsi:schemaLocation="urn:iec62325.351:tc57wg16:451-n:glskdocument:2:1 iec62325-451-n-glsk_v2_1.xsd" xmlns="urn:iec62325.351:tc57wg16:451-n:glskdocument:2:1" xmlns:xsi="http://www.
not necessary, since we want to test the absence of glsk

2025-01-13 09:27 UTC, Godelaine commented on monitoring/src/main/java/com/powsybl/openrao/monitoring/Monitoring.java
> +            throw new OpenRaoException(e);
2
Set failing status

2025-01-21 07:52 UTC, Godelaine approved these changes

2025-01-21 08:06 UTC, merged