Global balancing constraint
powsybl/powsybl-open-rao pull request #1250
Opened 2024-12-30 12:49 UTC by bqth29

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
Fixes #1052 

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2025-01-14 09:46 UTC, Godelaine requested changes

2025-01-14 09:46 UTC, Godelaine commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
> +
update comment with equation

2025-01-14 09:46 UTC, Godelaine commented on tests/src/test/resources/com/powsybl/openrao/tests/features/epic93_redispatching/US93_1.feature
> +Feature: US 93.1: Redispatching actions
great, very clear

2025-01-14 13:59 UTC, bqth29 commented on docs/castor/linear-problem/core-problem-filler.md
> +The network must remain balanced in terms of production and consumption after injection variations:
which variables should we define? because the equation only uses already existing ones

2025-01-17 08:42 UTC, Godelaine approved these changes

2025-01-17 09:04 UTC, merged