Add isSecure for RaoResult
powsybl/powsybl-open-rao pull request #869
Opened 2024-01-16 15:17 UTC by bqth29

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-01-18 09:03 UTC, pet-mit requested changes
Please update the documentation here: https://github.com/farao-community/farao-community.github.io/blob/master/pages/docs/output-data/rao-result/rao-result-json.md

i realize this is more complicated than it seemed. we may want to do some refactoring in the future. it would be nice to have a review from @phiedw too

2024-01-18 09:03 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +        return getCost(optimizedInstant) < 0;
virtual costs may include MNEC costs, LoopFlow costs, etc that do not count in security status. If you want to check divergence, check the computation status map first like you did with computation status
```suggestion
        return getFunctionalCost(optimizedInstant) < 0;
```

2024-01-18 09:03 UTC, pet-mit commented on data/rao-result/rao-result-impl/src/main/java/com/powsybl/openrao/data/raoresultimpl/RaoResultImpl.java
> +        if (ComputationStatus.FAILURE.equals(getComputationStatus())) {
also check computation status map

2024-01-18 10:59 UTC, murgeyseb commented on data/rao-result/rao-result-impl/src/main/java/com/powsybl/openrao/data/raoresultimpl/RaoResultImpl.java
> +                    if (flowCnecResults.keySet().stream().anyMatch(cnec -> getMargin(optimizedInstant, cnec, Unit.MEGAWATT) < 0)) {
The problem here is that there is nothing enforced in the API that tell that functional cost only refer to flow cnecs (even if in practice it is currently the case)

2024-01-22 09:27 UTC, pet-mit approved these changes

2024-01-22 09:41 UTC, merged