Multiple curative states
powsybl/powsybl-open-rao pull request #877
Opened 2024-01-25 12:44 UTC by bqth29

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-02-08 09:05 UTC, pet-mit requested changes

2024-02-08 09:05 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
> +        //LoadFlow.find("OpenLoadFlow").run(network, raoParameters.getLoadFlowAndSensitivityParameters().getSensitivityWithLoadFlowParameters().getLoadFlowParameters());
remove

2024-02-08 09:05 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
> +    void testCurative2Instant() {
change name

2024-02-12 16:36 UTC, pet-mit requested changes

2024-02-12 16:36 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/StateTree.java
> +        // - otherwise, add them all to the preventive perimeter
simplify and put in javadoc

2024-02-20 13:44 UTC, pet-mit requested changes

2024-02-20 13:44 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImplTest.java
> +    // TODO: add UT that checks the behaviour of findStateOptimizedFor
do this

2024-02-20 13:44 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImplTest.java
> +        when(crac.getInstantBefore(curativeInstant)).thenReturn(autoInstant);
at this point, I think we may as well replace all this with an actual crac creation

2024-02-21 09:45 UTC, pet-mit approved these changes

2024-02-21 09:53 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/StateTree.java
>       * If AUTO or CURATIVE state does not exist, it will not be optimized.
Should we update this description?

2024-02-21 09:59 UTC, merged