Add readmes
powsybl/powsybl-open-rao pull request #968
Opened 2024-04-11 13:39 UTC by pet-mit

Add some readme's:
- functional tests
- contributing

and fix some issues with existing doc

2024-04-11 16:06 UTC, phiedw requested changes

2024-04-11 16:06 UTC, phiedw commented on tests/README.md
> +#### Feature description
this whole paragraph has features and scenarii mixed up

2024-04-11 16:06 UTC, phiedw commented on tests/README.md
> +A feature is a collection of "steps", which is an instruction written in (almost) natural language, starting with `Given`,
Also need to change feature to scenario in this paragraph

2024-04-11 16:06 UTC, phiedw commented on tests/README.md
> +  specific configuration), and the new one, in two different features.
scenarios

2024-04-30 08:16 UTC, OpenSuze approved these changes

2024-04-30 08:16 UTC, OpenSuze commented on tests/README.md
> +   seperated according to their business type.
separated

2024-04-30 08:16 UTC, OpenSuze commented on tests/README.md
> +where `{string}` is a Gerkin input argument (that representes the timestamp).
represents

2024-04-30 08:16 UTC, OpenSuze commented on tests/README.md
> +- If you changed or improved some behavior and broke a test, you have to update it. Whenever possible, instead of only
you would have to update it

2024-04-30 15:54 UTC, OpenSuze approved these changes

2024-05-14 14:15 UTC, phiedw approved these changes

2024-05-14 14:28 UTC, merged